title: Ben Perche
tagline: Conductor — Championing New Voices
description: Conductor based in Australia, with a broad repertoire and a commitment to contemporary music.
baseurl: ""
url: "https://benperche.com"

author:
  name: Ben Perche
  email: benperche2@gmail.com  

# Social links
social:
  linkedin: https://www.linkedin.com/in/ben-perche-bb199a1a3/
  youtube: https://www.youtube.com/channel/UCq9RC5spTKDTUyw67Oher-A
  facebook: https://www.facebook.com/ben.perche.3

# Build settings
markdown: kramdown
permalink: pretty
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor

plugins:
  - jekyll-sitemap